name: Deploy to Server

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependency
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Zip build file
        run: |
            cd out
            zip -r build.zip

      - name: check build file
        run: ls -l
